name: user-service CI/CD

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      release_tag:
        description: 'Release Tag (e.g. v1.0.0)'
        required: true
        type: string

jobs:
  ci:
    if: github.event_name != 'workflow_dispatch'
    uses: L-and-D-Management-System/LnD/.github/workflows/reusable-ci.yaml@main
    with:
      service_name: user-service
      image_name: user-service
      dev_manifest_path: infra_new/argocd/dev/user-service.yaml
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      TOKEN: ${{ secrets.GHCR_PAT }}

  release:
    if: github.event_name == 'workflow_dispatch'
    uses: L-and-D-Management-System/LnD/.github/workflows/reusable-release.yaml@main
    with:
      release_tag: ${{ inputs.release_tag }}
      service_name: user-service
      dev_manifest_path: infra_new/argocd/dev/user-service.yaml
      prod_manifest_path: infra_new/argocd/prod/user-service.yaml
    secrets:
      TOKEN: ${{ secrets.GHCR_PAT }}